import { createFileRoute, Link } from "@tanstack/react-router";
import { CheckCircle2 } from "lucide-react";
import { Reveal, SectionHeading } from "@/components/reveal";
import { Button } from "@/components/ui/button";

export const Route = createFileRoute("/approach")({
  head: () => ({ meta: [{ title: "How We Work — Fikiri Communication" }, { name: "description", content: "Independent loyalty, CRM and data consulting, plus platform-agnostic technology advice." }] }),
  component: Approach,
});
const method = ["Diagnose — what problem are you actually solving, and what behaviour needs to change?", "Audit — an independent, benchmarked read on where you stand today.", "Analyse — the customer data behind the diagnosis: value, churn, frequency and segments.", "Design — the programme, marketing and data foundation in the right sequence.", "Model — cost of rewards, breakage, incremental revenue, ROI and payback.", "Support delivery — helping you land it, from stakeholder buy-in to frontline readiness."];
const platforms = ["Capillary", "Comarch", "Coniq", "Epsilon", "Xeno"];
function Approach() { return <div>
  <section className="relative overflow-hidden border-b border-border"><div className="aurora" aria-hidden="true" /><div className="relative mx-auto max-w-6xl px-5 py-20 sm:px-8"><Reveal><SectionHeading eyebrow="How we work" title="Consultants, not vendors" description="We challenge assumptions, back every recommendation with data, and are honest about what will and will not move your numbers." /></Reveal></div></section>
  <section className="mx-auto max-w-6xl px-5 py-20 sm:px-8"><Reveal><SectionHeading eyebrow="Our method" title="A deliberately sequenced approach" /></Reveal><div className="mt-10 grid gap-5 md:grid-cols-2 lg:grid-cols-3">{method.map((item, index) => <Reveal key={item} delay={index * .04}><div className="h-full rounded-2xl border border-border bg-card p-6 shadow-soft"><span className="font-display text-2xl font-bold text-emerald">0{index + 1}</span><p className="mt-4 text-sm leading-relaxed text-foreground">{item}</p></div></Reveal>)}</div></section>
  <section className="bg-surface py-20"><div className="mx-auto max-w-6xl px-5 sm:px-8"><Reveal><SectionHeading eyebrow="Technology & platforms" title="Platform-agnostic, by design" description="We do not sell software and are not tied to a vendor. Our recommendations follow your needs, systems and budget—not a sales target." /></Reveal><div className="mt-10 grid gap-4 sm:grid-cols-2 lg:grid-cols-5">{platforms.map((platform, index) => <Reveal key={platform} delay={index * .05}><div className="grid min-h-24 place-items-center rounded-2xl border border-border bg-card p-5 font-display text-lg font-semibold text-primary shadow-soft">{platform}</div></Reveal>)}</div><p className="mx-auto mt-8 max-w-3xl text-center text-sm leading-relaxed text-muted-foreground">Already running one of these—or something else entirely? We will help you get more from it. Choosing your first? We will help you choose well.</p></div></section>
  <section className="mx-auto max-w-6xl px-5 py-20 sm:px-8"><Reveal><div className="rounded-3xl border border-border bg-card p-8 shadow-soft"><h2 className="text-2xl font-semibold text-primary">What we believe</h2><ul className="mt-6 grid gap-4 md:grid-cols-2">{["Loyalty must balance customer value and profitability.", "Data comes first.", "Impact should be quantified.", "Strategy and execution are different disciplines."].map((belief) => <li key={belief} className="flex gap-3 text-sm text-foreground"><CheckCircle2 className="h-4 w-4 shrink-0 text-emerald" />{belief}</li>)}</ul><Button asChild variant="hero" className="mt-8"><Link to="/audit">Request an Audit</Link></Button></div></Reveal></section>
</div>; }
