import { Client } from "pg";

const connectionString = process.env.SUPABASE_DB_URL;

if (!connectionString) {
  console.error("Missing SUPABASE_DB_URL in environment.");
  process.exit(1);
}

const sql = `
create table if not exists public.articles (
  id bigint generated by default as identity primary key,
  title text not null,
  slug text not null unique,
  excerpt text,
  content text,
  category text not null default 'Loyalty',
  image text,
  tags text[] default '{}',
  reading_time text default '3 min read',
  status text not null default 'draft',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.articles enable row level security;

create policy "Public articles are viewable by everyone"
  on public.articles for select
  to anon, authenticated
  using (true);

create policy "Authenticated users can insert articles"
  on public.articles for insert
  to authenticated
  with check (true);

create policy "Authenticated users can update articles"
  on public.articles for update
  to authenticated
  using (true);

create policy "Authenticated users can delete articles"
  on public.articles for delete
  to authenticated
  using (true);
`;

async function main() {
  const client = new Client({ connectionString });

  try {
    await client.connect();
    await client.query(sql);
    console.log("Migration completed successfully.");
  } catch (error) {
    console.error("Migration failed:", error);
    process.exit(1);
  } finally {
    await client.end();
  }
}

main();
